all: AttributXML.cpp Document.cpp ElementBalise.cpp ElementTexte.cpp AbstractElement.cpp AttributXML.h Document.h ElementBalise.h ElementTexte.h AbstractElement.h makefile
	gcc -g -c *.cpp
	mv *.o ../../
clean:
